version: '3.8'

networks:
  rayen_public_net:
    driver: bridge
  rayen_private_net:
    driver: bridge
    internal: true
    name: rayen_red_compartida

volumes:
  ollama_data:
  grafana_data:
    driver: local

services:
  gateway:
    build:
      context: ./infraestructure/gateway
    container_name: rayen_gateway
    restart: unless-stopped
    ports:
      - "80:80" 
    networks:
      - rayen_public_net
      - rayen_private_net
    depends_on:
      frontend:
        condition: service_started
  
  frontend:
    build:
      context: ./services/frontend
    container_name: rayen_frontend
    restart: unless-stopped
    networks:
      - rayen_private_net
  
  backend:
    build:
      context: ./services/backend
    container_name: rayen_backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - rayen_private_net
  
  ivr-service:
    build:
      context: ./services/asterisk
    container_name: rayen_ivr
    restart: unless-stopped
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-10099:10000-10099/udp" # RTP (Audio)
    networks:
      - rayen_private_net
      - rayen_public_net 
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: rayen_cadvisor
    privileged: true
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - rayen_private_net

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: rayen_prometheus
    restart: unless-stopped
    volumes:
      - ./infraestructure/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - rayen_private_net
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana:10.4.1
    container_name: rayen_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - rayen_private_net
    depends_on:
      - prometheus




  ollama:
    image: ollama/ollama:latest
    container_name: rayen_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - rayen_public_net

  ollama-init:
    image: ollama/ollama:latest
    container_name: rayen_ollama_init
    volumes:
      - ollama_data:/root/.ollama
    depends_on:
      - ollama
    networks:
      - rayen_private_net
    # Usamos sh para ejecutar el pull después de una espera
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        echo "Esperando a que Ollama inicie..."
        sleep 10
        echo "Descargando modelo llama3..."
        ollama pull llama3
        echo "¡Descarga finalizada!"

  # 2. El microservicio de tu Chatbot (el que configuramos antes)
  chat-ia:
    build: 
      context: ./services/chatIA
      dockerfile: Dockerfile
    container_name: rayen_chat_ia
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - rayen_public_net


  