[ivr-rayen]
exten => 1000,1,Answer()
exten => 1000,n,Wait(1)

; 1. Reproduce el audio de bienvenida
exten => 1000,n,Playback(es/01-bienvenida)

; 2. Asterisk reproduce el audio del RUT y espera que el paciente digite los números
exten => 1000,n,Read(RUT_INGRESADO,es/02-pedir-rut,10,,1,10)

; 3. Dice "procesando" para que no quede en silencio incómodo mientras consulta a la API
exten => 1000,n,Playback(es/04-procesando)

; 4. Hacemos la consulta al Backend Node.js
exten => 1000,n,Set(RESPUESTA_API=${CURL(http://backend:5000/api/ivr/validar/${RUT_INGRESADO})})

; 5. Node.js devolverá un texto simple: "VALIDO" o "INVALIDO"
exten => 1000,n,GotoIf($["${RESPUESTA_API}" = "VALIDO"]?es-valido:es-invalido)

; --- Ruta: RUT Existe y tiene cita ---
exten => 1000,n(es-valido),Playback(es/05-exito)
exten => 1000,n,Hangup()

; --- Ruta: RUT No Existe ---
exten => 1000,n(es-invalido),Playback(es/06-error)
exten => 1000,n,Hangup()