[ivr-rayen]
exten => 1000,1,Answer()
exten => 1000,n,Wait(1)

exten => 1000,n(menu_principal),Read(OPCION_MENU,es/01-bienvenida,1,,1,5)

exten => 1000,n,GotoIf($["${OPCION_MENU}" = "1"]?opcion_agendar)
exten => 1000,n,GotoIf($["${OPCION_MENU}" = "2"]?opcion_anular)
exten => 1000,n,Goto(fallo)

exten => 1000,n(opcion_agendar),Read(RUT_INGRESADO,es/02-pedir-rut,10,,1,10)

exten => 1000,n,Read(TIPO_CITA,es/07-especialidad,1,,1,5)
exten => 1000,n,Playback(es/04-procesando)

exten => 1000,n,Set(RESPUESTA_API=${CURL(http://backend:5000/api/ivr/agendar?rut=${RUT_INGRESADO}&tipo=${TIPO_CITA})})
exten => 1000,n,GotoIf($["${RESPUESTA_API}" = "EXITO"]?exito:fallo)

exten => 1000,n(opcion_anular),Read(RUT_INGRESADO,es/02-pedir-rut,10,,1,10)

exten => 1000,n,Read(CONFIRMA_ANULAR,es/03-anular-conf,1,,1,5)

exten => 1000,n,GotoIf($["${CONFIRMA_ANULAR}" = "1"]?ejecutar_anulacion:cancelar_operacion)

exten => 1000,n(cancelar_operacion),Playback(es/06-error)
exten => 1000,n,Hangup()

exten => 1000,n(ejecutar_anulacion),Playback(es/04-procesando)

exten => 1000,n,Set(RESPUESTA_API=${CURL(http://backend:5000/api/ivr/anular?rut=${RUT_INGRESADO})})
exten => 1000,n,GotoIf($["${RESPUESTA_API}" = "EXITO"]?exito:fallo)

exten => 1000,n(exito),Playback(es/05-exito)
exten => 1000,n,Hangup()

exten => 1000,n(fallo),Playback(es/06-error)
exten => 1000,n,Hangup()
