[ivr-rayen]
exten => 1000,1,Answer()
exten => 1000,n,Wait(1)

; 1. Asterisk reproduce tu audio .wav y espera que el paciente digite 8 a 10 números
exten => 1000,n,Read(RUT_INGRESADO,ingrese-rutCAMBIARPORELWAV,10,,1,10)

; 2. Hacemos la consulta al Backend Node.js
; Al estar en contenedores, usamos el nombre del servicio en la URL
exten => 1000,n,Set(RESPUESTA_API=${CURL(http://backend:5000/api/ivr/validar/${RUT_INGRESADO})})

; 3. Node.js devolverá un texto simple: "VALIDO" o "INVALIDO"
exten => 1000,n,GotoIf($["${RESPUESTA_API}" = "VALIDO"]?es-valido:es-invalido)

; --- Ruta: RUT Existe y tiene cita ---
exten => 1000,n(es-valido),Playback(cita-confirmadaCAMBIARPORELWAV)
exten => 1000,n,Hangup()

; --- Ruta: RUT No Existe ---
exten => 1000,n(es-invalido),Playback(rut-incorrectoCAMBIARPORELWAV)
exten => 1000,n,Hangup()