[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.18.0.0/16
external_media_address=34.29.212.180
external_signaling_address=34.29.212.180

[1000]
type=endpoint
transport=transport-udp
context=ivr-rayen
disallow=all
allow=ulaw
allow=g722
allow=alaw
auth=1000
aors=1000
; --- PARCHES MÁGICOS PARA AUDIO EN DOCKER/ZOIPER ---
direct_media=no
force_rport=yes
rtp_symmetric=yes
rewrite_contact=yes
ice_support=yes

[1000]
type=auth
auth_type=userpass
password=rayen_secreto
username=1000

[1000]
type=aor
max_contacts=5
remove_existing=yes
