/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'header-fondo': '#E6E6EC',
        'surface': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#43474e',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#73777f',
        'outline-variant': '#c3c6cf',
        'surface-tint': '#3d608a',
        'primary': '#001b35',
        'on-primary': '#ffffff',
        'primary-container': '#003057',
        'on-primary-container': '#7699c5',
        'inverse-primary': '#a6c9f8',
        'secondary': '#006782',
        'on-secondary': '#ffffff',
        'secondary-container': '#42d0fe',
        'on-secondary-container': '#00566d',
        'tertiary': '#0d1c21',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#223136',
        'on-tertiary-container': '#89999f',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d2e4ff',
        'primary-fixed-dim': '#a6c9f8',
        'on-primary-fixed': '#001c37',
        'on-primary-fixed-variant': '#234871',
        'secondary-fixed': '#baeaff',
        'secondary-fixed-dim': '#5cd4ff',
        'on-secondary-fixed': '#001f29',
        'on-secondary-fixed-variant': '#004d62',
        'tertiary-fixed': '#d4e5eb',
        'tertiary-fixed-dim': '#b9c9cf',
        'on-tertiary-fixed': '#0e1e22',
        'on-tertiary-fixed-variant': '#3a494e',
        'background': '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe'
      },
      fontFamily: {
        sans: ['"Public Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px'
      },
      spacing: {
        'base': '8px',
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'margin': '32px'
      }
    },
  },
  plugins: [],
}