version: '3.8'

services:
  db-primary:
    image: mysql:8.0
    container_name: rayen_mysql_primary
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_primary:/var/lib/mysql
      - ./primary/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./init:/docker-entrypoint-initdb.d:ro
    networks:
      - rayen_private_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5

  db-replica:
    image: mysql:8.0
    container_name: rayen_mysql_replica
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3309:3306" 
    volumes:
      - mysql_data_replica:/var/lib/mysql
      - ./replica/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - rayen_private_net
    depends_on:
      db-primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5
  
  db-setup:
    image: mysql:8.0-debian
    env_file:
      - ../../.env
    volumes:
      - ../../scripts/deploy/setup-replication.sh:/setup.sh:ro
    # 3. Ejecutamos el archivo usando la ruta interna del contenedor
    command: /bin/bash /setup.sh
    container_name: rayen_mysql_setup
    networks:
      - rayen_private_net
      - rayen_public_net
    depends_on:
      db-primary:
        condition: service_healthy
      db-replica:
        condition: service_healthy

volumes:
  mysql_data_primary:
    driver: local
  mysql_data_replica:
    driver: local

networks:
  rayen_public_net:
    driver: bridge
  rayen_private_net:
    external: true
    name: rayen_red_compartida
